services:
  - type: web
    name: my-weasyprint-app
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 app:app
